<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $users = [
            [
                'name' => 'Kevin Wijaya',
                'username' => 'kevin_wijaya',
                'email' => 'kevin.wijaya@mail.com',
                'role' => 'author',
                'is_verified' => true,
                'status' => 'active',
                'institution' => 'Institut Teknologi Bandung',
                'phone' => '+6281234567890',
            ],
            [
                'name' => 'Nadia Putri Tanjung',
                'username' => 'nadia_putri',
                'email' => 'nadia.putri@mail.com',
                'role' => 'participant',
                'is_verified' => true,
                'status' => 'active',
                'institution' => 'Universitas Indonesia',
                'phone' => '+6281234567891',
            ],
            [
                'name' => 'Dr. Lin Wei',
                'username' => 'lin_wei',
                'email' => 'lin.wei@ntu.edu.sg',
                'role' => 'reviewer',
                'is_verified' => true,
                'status' => 'active',
                'institution' => 'Nanyang Technological University',
                'phone' => '+6591234567',
                'expertise' => 'AI, Machine Learning, Neural Networks',
            ],
            [
                'name' => 'Farhan Aditya',
                'username' => 'farhan_aditya',
                'email' => 'farhan.a@mail.com',
                'role' => 'author',
                'is_verified' => false,
                'status' => 'active',
                'institution' => 'Universitas Gadjah Mada',
                'phone' => '+6281234567892',
            ],
            [
                'name' => 'Grace Amelia',
                'username' => 'grace_amelia',
                'email' => 'grace.amelia@mail.com',
                'role' => 'participant',
                'is_verified' => false,
                'status' => 'blocked',
                'institution' => 'Universitas Airlangga',
                'phone' => '+6281234567893',
            ],
            [
                'name' => 'Prof. Amir Hidayat',
                'username' => 'amir_hidayat',
                'email' => 'hidayat@cendekia.ac.id',
                'role' => 'reviewer',
                'is_verified' => true,
                'status' => 'active',
                'institution' => 'Universitas Diponegoro',
                'phone' => '+6281234567894',
                'expertise' => 'Software Engineering, Cloud Computing',
            ],
            [
                'name' => 'Dinda Ayu',
                'username' => 'dinda_ayu',
                'email' => 'dinda.ayu@mail.com',
                'role' => 'author',
                'is_verified' => true,
                'status' => 'active',
                'institution' => 'Universitas Brawijaya',
                'phone' => '+6281234567895',
            ],
            [
                'name' => 'Rian Saputra',
                'username' => 'rian_saputra',
                'email' => 'rian.saputra@mail.com',
                'role' => 'participant',
                'is_verified' => false,
                'status' => 'active',
                'institution' => 'Universitas Padjadjaran',
                'phone' => '+6281234567896',
            ],
            [
                'name' => 'Dr. Maya Sartika',
                'username' => 'maya_sartika',
                'email' => 'maya.sartika@itb.ac.id',
                'role' => 'reviewer',
                'is_verified' => true,
                'status' => 'active',
                'institution' => 'Institut Teknologi Bandung',
                'phone' => '+6281234567897',
                'expertise' => 'Cyber Security, Cryptography',
            ],
            [
                'name' => 'Budi Santoso',
                'username' => 'budi_santoso',
                'email' => 'budi.santoso@ui.ac.id',
                'role' => 'author',
                'is_verified' => true,
                'status' => 'active',
                'institution' => 'Universitas Indonesia',
                'phone' => '+6281234567898',
            ],
            [
                'name' => 'Siti Nurhaliza',
                'username' => 'siti_nurhaliza',
                'email' => 'siti.nur@ugm.ac.id',
                'role' => 'participant',
                'is_verified' => true,
                'status' => 'active',
                'institution' => 'Universitas Gadjah Mada',
                'phone' => '+6281234567899',
            ],
            [
                'name' => 'Prof. Robert Jenkins',
                'username' => 'robert_jenkins',
                'email' => 'r.jenkins@oxford.ac.uk',
                'role' => 'reviewer',
                'is_verified' => true,
                'status' => 'active',
                'institution' => 'University of Oxford',
                'phone' => '+447911123456',
                'expertise' => 'Natural Language Processing, LLMs',
            ],
            [
                'name' => 'Agus Pratama',
                'username' => 'agus_pratama',
                'email' => 'agus.pratama@mail.com',
                'role' => 'author',
                'is_verified' => false,
                'status' => 'active',
                'institution' => 'Institut Teknologi Sepuluh Nopember',
                'phone' => '+6281234567800',
            ],
            [
                'name' => 'Clara Novita',
                'username' => 'clara_novita',
                'email' => 'clara.novita@mail.com',
                'role' => 'participant',
                'is_verified' => false,
                'status' => 'active',
                'institution' => 'Universitas Sebelas Maret',
                'phone' => '+6281234567801',
            ],
            [
                'name' => 'Dr. Hendra Gunawan',
                'username' => 'hendra_gunawan',
                'email' => 'hendra.gunawan@unpad.ac.id',
                'role' => 'reviewer',
                'is_verified' => true,
                'status' => 'active',
                'institution' => 'Universitas Padjadjaran',
                'phone' => '+6281234567802',
                'expertise' => 'Data Science, Big Data Analytics',
            ],
            [
                'name' => 'Eko Prasetyo',
                'username' => 'eko_prasetyo',
                'email' => 'eko.prasetyo@mail.com',
                'role' => 'author',
                'is_verified' => true,
                'status' => 'active',
                'institution' => 'Universitas Hasanuddin',
                'phone' => '+6281234567803',
            ],
            [
                'name' => 'Fitri Handayani',
                'username' => 'fitri_handayani',
                'email' => 'fitri.h@mail.com',
                'role' => 'participant',
                'is_verified' => true,
                'status' => 'active',
                'institution' => 'Universitas Andalas',
                'phone' => '+6281234567804',
            ],
            [
                'name' => 'Gilang Ramadhan',
                'username' => 'gilang_ramadhan',
                'email' => 'gilang.r@mail.com',
                'role' => 'author',
                'is_verified' => false,
                'status' => 'active',
                'institution' => 'Telkom University',
                'phone' => '+6281234567805',
            ],
            [
                'name' => 'Hana Yuliana',
                'username' => 'hana_yuliana',
                'email' => 'hana.yuliana@mail.com',
                'role' => 'participant',
                'is_verified' => true,
                'status' => 'active',
                'institution' => 'Universitas Udayana',
                'phone' => '+6281234567806',
            ],
            [
                'name' => 'Dr. Kenji Sato',
                'username' => 'kenji_sato',
                'email' => 'kenji.sato@u-tokyo.ac.jp',
                'role' => 'reviewer',
                'is_verified' => true,
                'status' => 'active',
                'institution' => 'The University of Tokyo',
                'phone' => '+81312345678',
                'expertise' => 'Computer Vision, Robotics',
            ],
            [
                'name' => 'Indra Kurniawan',
                'username' => 'indra_kurniawan',
                'email' => 'indra.k@mail.com',
                'role' => 'author',
                'is_verified' => true,
                'status' => 'active',
                'institution' => 'Universitas Bina Nusantara',
                'phone' => '+6281234567807',
            ],
            [
                'name' => 'Jessica Tan',
                'username' => 'jessica_tan',
                'email' => 'jessica.tan@mail.com',
                'role' => 'participant',
                'is_verified' => false,
                'status' => 'blocked',
                'institution' => 'Universitas Multimedia Nusantara',
                'phone' => '+6281234567808',
            ],
            [
                'name' => 'Lukman Hakim',
                'username' => 'lukman_hakim',
                'email' => 'lukman.hakim@mail.com',
                'role' => 'author',
                'is_verified' => true,
                'status' => 'active',
                'institution' => 'Universitas Syiah Kuala',
                'phone' => '+6281234567809',
            ],
            [
                'name' => 'Mega Puspita',
                'username' => 'mega_puspita',
                'email' => 'mega.p@mail.com',
                'role' => 'participant',
                'is_verified' => true,
                'status' => 'active',
                'institution' => 'Universitas Lampung',
                'phone' => '+6281234567810',
            ],
        ];

        foreach ($users as $userData) {
            User::updateOrCreate(
                ['email' => $userData['email']],
                array_merge($userData, [
                    'password' => Hash::make('password'),
                    'avatar' => 'https://api.dicebear.com/7.x/adventurer/svg?seed=' . urlencode($userData['name']) . '&backgroundColor=f8c0a8',
                ])
            );
        }
    }
}
